### ISSUE TITLE
undefined reference to symbol 'glMaterialfv'

### ISSUE THREAD

**Issue by nishantgrover** [YANG-H/Teddy#2]
I have been getting this error for a while and haven't been able to find a solution.
I ran make and this is the error I got:-
[ 91%] Linking CXX executable Teddy
/usr/bin/ld: CMakeFiles/Teddy.dir/tcanvas.cpp.o: undefined reference to symbol 'glMaterialfv'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]:  [lib/CMakeFiles/Teddy.dir/build.make:265: lib/Teddy] Error 1
make[1]:  [CMakeFiles/Makefile2:114: lib/CMakeFiles/Teddy.dir/all] Error 2
make: *** [Makefile:114: all] Error 2

**Comment by xrachitx** [comment]
Same is happening with me. Please look into it.
